# Set to true to add assignees to pull requests
addAssignees: true
addReviewers: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - augustorcn
  - dhferraz
  - F3lip3
  - robsonferrll

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1
numberOfAssignees: 2
