# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: fri
canPublishIssues: false
canPublishPullRequests: true
canPublishContributors: true
canPublishStargazers: true
canPublishCommits: true
